[book]
authors = ["wo4mei3"]
language = "ja"
multilingual = false
src = "src"
title = "The Mic Programming Language"

[output.xgettext]
pot-file = "messages.pot"

[output.html]
additional-js = ["theme/custom-highlight.js"]
google-analytics = "G-L18H2R258B"